version: "3.8"

services:
  # https://documentation.portainer.io/v2.0/deploy/ceinstalldocker/
  edc_portainer:
    container_name: edc_portainer
    image: portainer/portainer-ce
    restart: always
    ports:
        - ${PORTAINER_PORT:-9000}:9000
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock 
        - PortainerData:/data

volumes:
    PortainerData:

networks:
  default:
    external:
      name: edcNet
